USE ACTIVIDAD_1_2_20241C
GO
CREATE TABLE INSTRUCTORES(
     ID_INSTRUCTOR INT NOT NULL,
     ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO),
     PRIMARY KEY(ID_INSTRUCTOR),
     UNIQUE(ID_USUARIO),
)
GO
  CREATE TABLE CURSO_X_INSTRUCTORES(
      ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
      ID_INSTRUCTOR INT NOT NULL FOREIGN KEY REFERENCES INSTRUCTORES(ID_INSTRUCTOR),
      PRIMARY KEY (ID_CURSO, ID_INSTRUCTOR),
  )