USE ACTIVIDAD_1_2_20241C
GO
CREATE TABLE FORMATO_IDIOMA(
ID_FORMATO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL, 
)
GO
ALTER TABLE CURSO_X_IDIOMA
--ADD IDFORMATO INT NOT NULL FOREIGN KEY REFERENCES FORMATO_IDIOMA(ID_FORMATO)
ADD CONSTRAINT PK_IDIOMAS_FORMATO PRIMARY KEY (ID_CURSO, ID_IDIOMA, IDFORMATO)

