USE ACTIVIDAD_1_2_20241C
GO
CREATE TABLE NIVELES(
ID_NIVEL INT NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL, 
)
GO
ALTER TABLE CURSOS
ADD CONSTRAINT FK_NIVEL_CURSOS FOREIGN KEY (NIVEL) REFERENCES NIVELES(ID_NIVEL)