CREATE DATABASE ACTIVIDAD_1_2_20241C
GO
USE ACTIVIDAD_1_2_20241C
GO
CREATE TABLE CURSOS(
    ID_CURSO INT NOT NULL PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(50) NOT NULL,
    FECHA_ESTRENO DATE NOT NULL,
    COSTO_CURSADO MONEY NOT NULL,
    COSTO_CERTIFICACION MONEY NOT NULL,
    NIVEL INT NULL,
)
GO
CREATE TABLE CLASES(
    ID_CLASE INT NOT NULL PRIMARY KEY,
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    NOMBRE VARCHAR(50) NOT NULL,
    NUMERO INT NOT NULL,
    DURACION INT NOT NULL, 
)
GO
CREATE TABLE TIPOS_CONTENIDO(
    ID_TIPO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
)
GO
CREATE TABLE CONTENIDO(
    ID_CONTENIDO INT NOT NULL PRIMARY KEY,
    ID_CLASE INT NOT NULL FOREIGN KEY REFERENCES CLASES(ID_CLASE),
    NOMBRE VARCHAR(50) NOT NULL,
    ID_TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPOS_CONTENIDO(ID_TIPO),
    TAMANIO BIGINT NOT NULL, 
)
GO
CREATE TABLE IDIOMA(
    ID_IDIOMA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
    TIPO VARCHAR(50) NOT NULL, 
)
GO
CREATE TABLE CURSO_X_IDIOMA(
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    ID_IDIOMA INT NOT NULL FOREIGN KEY REFERENCES IDIOMA(ID_IDIOMA),
    PRIMARY KEY (ID_CURSO, ID_IDIOMA),
)
GO
CREATE TABLE CATEGORIAS(
    ID_CATEGORIA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
)
GO
CREATE TABLE CURSO_X_CATEGORIA(
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    ID_CATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID_CATEGORIA),
    PRIMARY KEY (ID_CURSO, ID_CATEGORIA),
)
GO
CREATE TABLE USUARIOS(
    ID_USUARIO INT NOT NULL PRIMARY KEY,
    APELLIDO VARCHAR(50) NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    MAIL VARCHAR(100) NOT NULL UNIQUE,
    GENERO VARCHAR(50) NULL,
    NOMBRE_USUSARIO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(50) NULL,
    CELULAR VARCHAR(50) NULL,
)
GO
CREATE TABLE INFO_PERSONAL(
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO),
    PRIMARY KEY(ID_USUARIO),
    DOMICILIO VARCHAR(100) NOT NULL,
    CP INT NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    CIUDAD VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE INSTRUCTORES(
    ID_INSTRUCTOR INT NOT NULL,
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO),
    PRIMARY KEY(ID_USUARIO, ID_INSTRUCTOR),
)
GO
 CREATE TABLE CURSO_X_INSTRUCTORES(
     ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
     ID_INSTRUCTOR INT NOT NULL FOREIGN KEY REFERENCES INSTRUCTORES(ID_INSTRUCTOR),
     PRIMARY KEY (ID_CURSO, ID_INSTRUCTOR),
 )
GO
CREATE TABLE INSCRIPCIONES(
    ID_INSCRIPCION INT NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO), 
    ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID_CURSO),
    FECHA_INSCRIPCION DATE NOT NULL,
)
GO
CREATE TABLE PAGOS(
    ID_INSCRIPCION INT NOT NULL FOREIGN KEY REFERENCES INSCRIPCIONES(ID_INSCRIPCION),
    NUM_PAGO INT NOT NULL,
    PRIMARY KEY(ID_INSCRIPCION, NUM_PAGO),
    MONTO MONEY NOT NULL, 
    FECHA_PAGO DATE NOT NULL,
)
GO
CREATE TABLE RESENIAS(
    ID_INSCRIPCION INT NOT NULL FOREIGN KEY REFERENCES INSCRIPCIONES(ID_INSCRIPCION),
    PRIMARY KEY(ID_INSCRIPCION),
    RESENIA VARCHAR(200) NOT NULL, 
)
GO
CREATE TABLE CERTIFICACIONES(
    ID_INSCRIPCION INT NOT NULL FOREIGN KEY REFERENCES INSCRIPCIONES(ID_INSCRIPCION),
    PRIMARY KEY(ID_INSCRIPCION),
    COSTO MONEY NOT NULL, 
    FECHA_CERTIFICADO DATE NOT NULL,
)